### PR TITLE
Fix publisher pc not resumed if no data channel published

### LINKED ISSUE #229: Reconnected, but not really
We have a livestreamer program inside a robot that streams the video to people who watch in the browser. We log reconnect and disconnect like so:

```golang
OnReconnected: func() {
	LOG.Info("reconnected to room")
},
OnReconnecting: func() {
	LOG.Info("reconnecting to room")
},
OnDisconnected: func() {
	LOG.Info("disconnected from room")
	// cleanup and restart connection omitted
},
```

When the internet connection is interrupted, the client tries to re-connect. I have seen this work well, but sometimes the livekit sdk thinks it successfully reconnected but no media (video & audio) comes through. This happened:

```
// before this moment everything works beautifully
// at 22:22:39 we have a network interruption.
2023/05/15 22:22:41 "level"=0 "msg"="ICE disconnected"
2023/05/15 22:23:05 "level"=0 "msg"="ICE failed"
22:23:05	INFO	reconnecting to room
2023/05/15 22:23:05 "level"=0 "msg"="resuming connection..." "reconnectCount"=0
2023/05/15 22:23:11 "level"=0 "msg"="received offer for subscriber"
2023/05/15 22:23:11 "level"=0 "msg"="ICE connected"
22:23:11	INFO	reconnected to room
22:23:14	INFO	reconnecting to room
2023/05/15 22:23:14 "level"=0 "msg"="resuming connection..." "reconnectCount"=0
2023/05/15 22:23:14 "level"=0 "msg"="received offer for subscriber"
2023/05/15 22:23:14 "level"=0 "msg"="remote offer restart ice while ice gathering"
22:23:14	INFO	reconnected to room
2023/05/15 22:23:16 "level"=0 "msg"="accept remote restart ice offer after ICE gathering"

// We know from other system logs that from 22:22:45 on the internet was all good again.
2023/05/15 22:23:46 "level"=0 "msg"="ICE failed"
22:23:46	INFO	reconnecting to room
2023/05/15 22:23:46 "level"=0 "msg"="resuming connection..." "reconnectCount"=0
2023/05/15 22:23:46 "level"=0 "msg"="received offer for subscriber"
2023/05/15 22:23:46 "level"=0 "msg"="ICE connected"
22:23:46	INFO	reconnected to room

// Around 22:23 participants report that the image froze. After a webpage refresh they see only a black screen.
// At 22:24:53 an engineer confirms the issue and restart the go-program, restoring the stream. 
```

It seems like Livekit _thinks_ it is connected, but it isn't.

These are the screenshots from Livekit dashboard:

image
image

1. Any idea what the problem could be?
 
2. Is there any extra logging that we could enable to help find the root cause? I'm happy to add extra logs in production so that when this happens again we better understand the problem.

3. As a workaround, are there any metrics/hooks in this sdk that we could use to detect this situation? Maybe there is a way to see the number of frames arrived at the participants, and we could compare that to the number of frames sent, to automatically force-restart?

### PR DESCRIPTION
**Pull request by cnderrauber**
The RTCEngine relies on `hasPublished` variable to restart ice for publisher pc, but it is only set in data publishing, that is not correct. Fix #229

### CODE REVIEW

File: engine.go [hunk 1]
```diff
@@ -418,7 +417,6 @@ func (e *RTCEngine) handleDisconnect(fullReconnect bool) {
 				logger.Infow("resuming connection...", "reconnectCount", reconnectCount)
 				if err := e.resumeConnection(); err != nil {
 					logger.Errorw("resume connection failed", err)
-					fullReconnect = true
```
Comment (cnderrauber) [inline engine.go:421]: let sdk has chance to retry resume

**Review by boks1971 — APPROVED** [review]
